# Generated by Django 3.0.5 on 2020-05-10 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='nome',
            new_name='cargo',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='nome',
            new_name='servico',
        ),
    ]
