# Generated by Django 3.0.5 on 2020-05-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='posicao',
            field=models.CharField(choices=[('esq', 'Esquerda'), ('dir', 'Direita')], default='Esquerda', max_length=10, verbose_name='Posição'),
        ),
    ]
