# Generated by Django 3.0.5 on 2020-05-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_features_posicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='posicao',
            field=models.CharField(choices=[('Esquerda', 'esquerda'), ('Direita', 'direita')], default='Esquerda', max_length=10, verbose_name='Posição'),
        ),
    ]
